############################################################################
###                     Main-processor-service properties                ###
############################################################################
server:
  # 8080 -- default port
  port: 8080
  # defining url for app
  servlet:
    context-path: /pet/v1/main-processor-service

spring:
  application:
    # service name(can be used in discovery to refer by its name)
    name: main-processor-service
  # setting custom banner instead of regular
  banner:
    location: main-processor-banner.txt

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    #    security_instance
    username: Final
    password: FANTASY
  jpa:
    #    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

eureka:
  client:
    serviceUrl:
      # Url for a discovery service
      defaultZone: http://localhost:8761/pet/v1/discovery-service/eureka
  instance:
    # Flag to say that, when guessing a hostname,
    # the IP address of the server should be used in preference to the hostname reported by the OS. // From docs
    preferIpAddress: true

#security:
#  oauth2:
#    client:
#      client-id: main-processor-service
#      client-secret: vFantasticFour4
#      access-token-uri: http://localhost:4343/pet/v1/security-service/oauth/token
#
##    client pass: vFantasticFour4