package com.iba.mainprocessor.entity;

public enum Category {
    ANY, PHONE, LAPTOP, COMPUTER, MONITOR, PRINTER, KEYBOARD, MOUSE, USB_FLASH_DRIVE, CABLE, VIDEO_CARD, RAM, MOTHERBOARD, COOLER, PROCESSOR, HARD_DRIVE, SSD
}
