############################################################################
###                     Email-sender-service properties                  ###
############################################################################
server:
  # 25 -- default port for smtp
  port: 2525
  # defining url for app
  servlet:
    context-path: /pet/v1/email-sender-service

spring:
  rabbitmq:
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
#    port: 15672

  application:
    # service name(can be used in discovery to refer by its name)
    name: email-sender-service
  # setting custom banner instead of regular
  banner:
    location: email-sender-banner.txt
  data:
    # configuration of mongoDB
    mongodb:
      authentication-database: admin
      # db name
      database: mail
      # default port for mongoDB: 27017
      port: 27017
      host: localhost
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}

  # mail config
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    serviceUrl:
      # Url for a discovery service
      defaultZone: http://localhost:8761/pet/v1/discovery-service/eureka
  instance:
    # Flag to say that, when guessing a hostname,
    # the IP address of the server should be used in preference to the hostname reported by the OS. // From docs
    preferIpAddress: true